# Generated by Django 6.0.2 on 2026-04-17 16:37

import django.db.models.deletion
import portal.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0030_alter_termenprocedural_tip_termen'),
        ('documents', '0006_acturmarire_data_semnarii_acturmarire_este_semnat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CerereAccesPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_solicitant', models.CharField(max_length=200)),
                ('cnp_solicitant', models.CharField(max_length=13)),
                ('email_solicitant', models.EmailField(max_length=254)),
                ('motiv_solicitare', models.TextField(help_text='Descrieți pe scurt motivul pentru care solicitați accesul la dosar', verbose_name='Motivul solicitării')),
                ('data_cererii', models.DateTimeField(auto_now_add=True)),
                ('stare', models.CharField(choices=[('IN_ASTEPTARE', 'În așteptare'), ('APROBATA', 'Aprobată'), ('RESPINSA', 'Respinsă')], default='IN_ASTEPTARE', max_length=20)),
                ('data_procesarii', models.DateTimeField(blank=True, null=True)),
                ('motiv_respingere', models.CharField(blank=True, choices=[('CALITATE', 'Calitate procesuală incompatibilă cu accesul la dosar'), ('FAZA', 'Dosarul se află într-o fază incompatibilă cu consultarea'), ('INCOMPLETE', 'Date de identificare incomplete sau incorecte'), ('ALTUL', 'Alt motiv')], max_length=20, null=True)),
                ('motiv_respingere_detalii', models.TextField(blank=True, null=True, verbose_name='Detalii suplimentare (opțional)')),
                ('aprobata_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cereri_portal_procesate', to=settings.AUTH_USER_MODEL)),
                ('dosar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cereri_acces_portal', to='cases.dosar')),
                ('parte', models.ForeignKey(blank=True, help_text='Completat automat la validarea CNP-ului', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cereri_acces_portal', to='cases.parteimplicata')),
            ],
            options={
                'verbose_name': 'Cerere Acces Portal',
                'verbose_name_plural': 'Cereri Acces Portal',
                'ordering': ['-data_cererii'],
            },
        ),
        migrations.CreateModel(
            name='AccesPortalParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_acces', models.CharField(default=portal.models.genereaza_cod, max_length=20, unique=True)),
                ('pin_hash', models.CharField(max_length=128)),
                ('data_expirare', models.DateField()),
                ('activ', models.BooleanField(default=True)),
                ('documente_accesibile', models.ManyToManyField(blank=True, related_name='accese_portal', to='documents.acturmarire', verbose_name='Documente accesibile')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_portal', to='cases.parteimplicata')),
                ('cerere', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acces_generat', to='portal.cerereaccesportal')),
            ],
            options={
                'verbose_name': 'Acces Portal Parte',
                'verbose_name_plural': 'Accese Portal Părți',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccesPortalParte',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cod_acces', models.CharField(db_index=True, default=portal.models.genereaza_cod, max_length=20)),
                ('pin_hash', models.CharField(max_length=128)),
                ('data_expirare', models.DateField()),
                ('activ', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cerere', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portal.cerereaccesportal')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parte', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.parteimplicata')),
            ],
            options={
                'verbose_name': 'Istoric Acces Portal',
                'verbose_name_plural': 'historical Accese Portal Părți',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCerereAccesPortal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nume_solicitant', models.CharField(max_length=200)),
                ('cnp_solicitant', models.CharField(max_length=13)),
                ('email_solicitant', models.EmailField(max_length=254)),
                ('motiv_solicitare', models.TextField(help_text='Descrieți pe scurt motivul pentru care solicitați accesul la dosar', verbose_name='Motivul solicitării')),
                ('data_cererii', models.DateTimeField(blank=True, editable=False)),
                ('stare', models.CharField(choices=[('IN_ASTEPTARE', 'În așteptare'), ('APROBATA', 'Aprobată'), ('RESPINSA', 'Respinsă')], default='IN_ASTEPTARE', max_length=20)),
                ('data_procesarii', models.DateTimeField(blank=True, null=True)),
                ('motiv_respingere', models.CharField(blank=True, choices=[('CALITATE', 'Calitate procesuală incompatibilă cu accesul la dosar'), ('FAZA', 'Dosarul se află într-o fază incompatibilă cu consultarea'), ('INCOMPLETE', 'Date de identificare incomplete sau incorecte'), ('ALTUL', 'Alt motiv')], max_length=20, null=True)),
                ('motiv_respingere_detalii', models.TextField(blank=True, null=True, verbose_name='Detalii suplimentare (opțional)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aprobata_de', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dosar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.dosar')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parte', models.ForeignKey(blank=True, db_constraint=False, help_text='Completat automat la validarea CNP-ului', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.parteimplicata')),
            ],
            options={
                'verbose_name': 'Istoric Cerere Portal',
                'verbose_name_plural': 'historical Cereri Acces Portal',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='JurnalAccesPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('sectiune', models.CharField(default='Vizualizare dosar', max_length=100)),
                ('acces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurnal', to='portal.accesportalparte')),
            ],
            options={
                'verbose_name': 'Jurnal Acces Portal',
                'verbose_name_plural': 'Jurnal Accese Portal',
                'ordering': ['-timestamp'],
            },
        ),
    ]
