"""
Django settings for cms_penal project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os # Folosit pentru a salva fisierele media (word, pdf); se poate folosi și BASE_DIR direct.
from pathlib import Path
from dotenv import load_dotenv

# Încărcăm variabilele din fișierul .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'cheie-de-rezerva-nesigura')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == 'True'

# Default este ALLOWED_HOSTS = []. Am adăugat "*" pentru testare pe server
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'cases',
    'documents',
    'portal',
    'simple_history', # pentru audit (istoric modificări)
    'sass_processor', # leaga codul sass in Django
    'django_otp',
    'django_otp.plugins.otp_totp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware', # pentru a înregistra cine a făcut modificări în istoric
    'accounts.middleware.Force2FAMiddleware',
]

ROOT_URLCONF = 'cms_penal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Calea pentru notificari
                'cases.context_processors.notificari_globale',
            ],
        },
    },
]

WSGI_APPLICATION = 'cms_penal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ro'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Folderul care va conține fișierele pentru producție (LXC) după rularea "collectstatic"
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Django va căuta fișiere (fonturi, imagini) în acest folder
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# --- SETĂRI NOI PENTRU SASS ---

# Îi spunem lui Django ce "căutători" (finders) să folosească pentru a găsi fișierele.
# Am adăugat CssFinder la final pentru ca Django să știe să proceseze SCSS-ul.
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder',
]

# Locul unde django-sass-processor va salva fișierele .css după ce le compilează din .scss
SASS_PROCESSOR_ROOT = BASE_DIR / 'static'

# Specificăm modelul de utilizator personalizat
AUTH_USER_MODEL = 'accounts.CustomUser'

# URL-ul prin care vom accesa fișierele în browser (ex: /media/ordonanta.pdf)
MEDIA_URL = '/media/'

# Locația fizică de pe disc unde se vor salva fișierele
MEDIA_ROOT = BASE_DIR / 'media'

# După un login cu succes, mergem pe dashboard!
LOGIN_REDIRECT_URL = 'cases:dashboard'

# După deconectare, ne întoarcem la pagina de login
LOGOUT_REDIRECT_URL = 'login'

# Dacă încercăm să accesăm o pagină care necesită autentificare, dar nu suntem logați, vom fi redirecționați către pagina de login
LOGIN_URL = 'login'

# Închidem sesiunea după ce închidem browserul pentru a nu ne păstra logaţi
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ==========================================
# CONFIGURARE JAZZMIN (TEMA ADMIN)
# ==========================================
JAZZMIN_SETTINGS = {
    "site_title": "CMS Penal Admin",
    "site_header": "Registrul Dosarelor",
    "site_brand": "Admin",
    "welcome_sign": "Autentificare Sistem Gestiune Dosare",
    "copyright": "Proiect Licență",
    
    # Căutare globală rapidă din bara de sus a adminului
    "search_model": ["cases.Dosar", "accounts.CustomUser"],
    
    # Meniu lateral
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Iconițe FontAwesome
    "icons": {
        "auth": "fas fa-users-cog",
        "accounts.CustomUser": "fas fa-user-shield",
        "cases.Dosar": "fas fa-folder-open",
        "cases.ParteImplicata": "fas fa-users",
        "cases.Infractiune": "fas fa-gavel",
        "cases.MasuraPreventiva": "fas fa-lock",
        "documents.ActUrmarire": "fas fa-file-alt",
        "simple_history.historicaldosar": "fas fa-history",
    },
    
    # Buton plasat jos în panoul admin care permite schimbarea culorilor live
    "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly", 
    
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
    }
}

# SETĂRI PENTRU 2FA - CATEGORII DE UTILIZATORI PENTRU CARE 2FA ESTE OBLIGATORIU
MANDATORY_2FA_ROLES = ['PROCUROR', 'ADMIN']

# CHEIA DE CRIPTARE PENTRU DATELE SENSIBILE (CNP)
# Cheia de criptare trebuie transformată înapoi în format "bytes"
ENCRYPTION_KEY = os.environ.get('ENCRYPTION_KEY').encode('utf-8')


# CONFIGURARE SERVER DE EMAIL (SMTP GMAIL)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Citim adresa și parola în siguranță din fișierul .env
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

# Adresa care va apărea la "Expeditor" când utilizatorul primește mailul
DEFAULT_FROM_EMAIL = f"SED <{EMAIL_HOST_USER}>"

# Adaugat la componenta PORTAL
# URL-ul de bază al aplicației (folosit în emailuri)
SITE_URL = 'http://localhost:8000'  # în producție: 'https://domeniu.ro'

# CONFIGURARE SERVICII GEOGRAFICE
# Setăm un fallback sigur către OpenStreetMap standard în caz că lipsește din .env
MAP_TILE_SERVER_URL = os.environ.get(
    'MAP_TILE_SERVER_URL', 
    'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
)