# Generated by Django 6.0.2 on 2026-02-23 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_unic', models.CharField(help_text='Ex: 123/P/2026', max_length=50, unique=True)),
                ('data_inregistrarii', models.DateField(auto_now_add=True)),
                ('infractiune_cercetata', models.TextField(help_text='Descrierea faptei și încadrarea juridică (ex: Furt calificat, art. 229 C.pen)')),
                ('stadiu', models.CharField(choices=[('IN_LUCRU', 'În lucru la Poliție'), ('LA_PROCUROR', 'Înaintat la Procuror'), ('CLASAT', 'Clasat'), ('TRIMIS_IN_JUDECATA', 'Trimis în judecată'), ('SUSPENDAT', 'Suspendat')], default='IN_LUCRU', max_length=20)),
                ('ofiter_caz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosare_instrumentate', to=settings.AUTH_USER_MODEL)),
                ('procuror_caz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosare_supravegheate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dosar Penal',
                'verbose_name_plural': 'Dosare Penale',
                'ordering': ['-data_inregistrarii'],
            },
        ),
        migrations.CreateModel(
            name='ParteImplicata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_complet', models.CharField(max_length=150)),
                ('cnp', models.CharField(blank=True, max_length=13, null=True, verbose_name='CNP')),
                ('calitate_procesuala', models.CharField(choices=[('SUSPECT', 'Suspect'), ('INCULPAT', 'Inculpat'), ('PARTE_VATAMATA', 'Parte Vătămată'), ('PARTE_CIVILA', 'Parte Civilă'), ('MARTOR', 'Martor')], max_length=20)),
                ('mentiuni', models.TextField(blank=True, help_text='Alte date de contact, antecedente, etc.', null=True)),
                ('dosar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parti_implicate', to='cases.dosar')),
            ],
            options={
                'verbose_name': 'Parte Implicată',
                'verbose_name_plural': 'Părți Implicate',
            },
        ),
    ]
