# Generated by Django 6.0.2 on 2026-02-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_dosar_grefier_caz'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosar',
            name='data_solutiei',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosar',
            name='tip_solutie',
            field=models.CharField(blank=True, choices=[('TRIMITERE', 'Trimitere în judecată'), ('CLASARE', 'Clasare'), ('RENUNTARE', 'Renunțare la urmărirea penală'), ('DECLINARE', 'Declinare'), ('SUSPENDARE', 'Suspendare'), ('TRECERE', 'Trecere la alt organ')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dosar',
            name='stadiu',
            field=models.CharField(choices=[('POLITIE', 'În lucru la Poliție'), ('PROCUROR', 'În lucru la Procuror'), ('SOLUTIONAT', 'Soluționat')], default='POLITIE', max_length=20),
        ),
    ]
