# Generated by Django 6.0.2 on 2026-02-26 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_dosar_data_solutiei_dosar_tip_solutie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infractiune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incadrare_juridica', models.CharField(help_text='Ex: Furt calificat', max_length=255)),
                ('articol_penal', models.CharField(help_text='Ex: art. 228-229 C.pen.', max_length=100)),
                ('data_comiterii', models.DateField(blank=True, help_text='Data presupusei fapte', null=True)),
                ('dosar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractiuni', to='cases.dosar')),
            ],
        ),
    ]
