# Generated by Django 6.0.2 on 2026-02-26 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_infractiune'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasuraPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_masura', models.CharField(choices=[('RETINERE', 'Reținere (24h)'), ('AREST_PREVENTIV', 'Arest Preventiv'), ('AREST_DOMICILIU', 'Arest la Domiciliu'), ('CONTROL_JUDICIAR', 'Control Judiciar'), ('CONTROL_JUDICIAR_CAUTIUNE', 'Control Judiciar pe Cauțiune')], max_length=50)),
                ('durata_zile', models.PositiveIntegerField(help_text='Numărul de zile (ex: 30)')),
                ('data_inceput', models.DateField()),
                ('data_sfarsit', models.DateField()),
                ('dosar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masuri_preventive', to='cases.dosar')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masuri_preventive', to='cases.parteimplicata')),
            ],
        ),
    ]
