# Generated by Django 6.0.2 on 2026-03-04 15:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_masurapreventiva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDosar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numar_unic', models.CharField(db_index=True, help_text='Ex: 123/P/2026', max_length=50)),
                ('data_inregistrarii', models.DateField(blank=True, editable=False)),
                ('infractiune_cercetata', models.TextField(help_text='Descrierea faptei și încadrarea juridică (ex: Furt calificat, art. 229 C.pen)')),
                ('stadiu', models.CharField(choices=[('POLITIE', 'În lucru la Poliție'), ('PROCUROR', 'În lucru la Procuror'), ('SOLUTIONAT', 'Soluționat')], default='POLITIE', max_length=20)),
                ('tip_solutie', models.CharField(blank=True, choices=[('TRIMITERE', 'Trimitere în judecată'), ('CLASARE', 'Clasare'), ('RENUNTARE', 'Renunțare la urmărirea penală'), ('DECLINARE', 'Declinare'), ('SUSPENDARE', 'Suspendare'), ('TRECERE', 'Trecere la alt organ')], max_length=20, null=True)),
                ('data_solutiei', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('grefier_caz', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ofiter_caz', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('procuror_caz', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Dosar Penal',
                'verbose_name_plural': 'historical Dosare Penale',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInfractiune',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('incadrare_juridica', models.CharField(help_text='Ex: Furt calificat', max_length=255)),
                ('articol_penal', models.CharField(help_text='Ex: art. 228-229 C.pen.', max_length=100)),
                ('data_comiterii', models.DateField(blank=True, help_text='Data presupusei fapte', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dosar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.dosar')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical infractiune',
                'verbose_name_plural': 'historical infractiunes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMasuraPreventiva',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tip_masura', models.CharField(choices=[('RETINERE', 'Reținere (24h)'), ('AREST_PREVENTIV', 'Arest Preventiv'), ('AREST_DOMICILIU', 'Arest la Domiciliu'), ('CONTROL_JUDICIAR', 'Control Judiciar'), ('CONTROL_JUDICIAR_CAUTIUNE', 'Control Judiciar pe Cauțiune')], max_length=50)),
                ('durata_zile', models.PositiveIntegerField(help_text='Numărul de zile (ex: 30)')),
                ('data_inceput', models.DateField()),
                ('data_sfarsit', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dosar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.dosar')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parte', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.parteimplicata')),
            ],
            options={
                'verbose_name': 'historical masura preventiva',
                'verbose_name_plural': 'historical masura preventivas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalParteImplicata',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nume_complet', models.CharField(max_length=150)),
                ('cnp', models.CharField(blank=True, max_length=13, null=True, verbose_name='CNP')),
                ('calitate_procesuala', models.CharField(choices=[('SUSPECT', 'Suspect'), ('INCULPAT', 'Inculpat'), ('PARTE_VATAMATA', 'Parte Vătămată'), ('PARTE_CIVILA', 'Parte Civilă'), ('MARTOR', 'Martor')], max_length=20)),
                ('mentiuni', models.TextField(blank=True, help_text='Alte date de contact, antecedente, etc.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dosar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.dosar')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Parte Implicată',
                'verbose_name_plural': 'historical Părți Implicate',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
