# Generated by Django 6.0.2 on 2026-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_historicaldosar_historicalinfractiune_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldosar',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Istoric Dosar', 'verbose_name_plural': 'historical Dosare Penale'},
        ),
        migrations.AlterModelOptions(
            name='historicalinfractiune',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Istoric Infracțiune', 'verbose_name_plural': 'historical Infracțiuni'},
        ),
        migrations.AlterModelOptions(
            name='historicalmasurapreventiva',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Istoric Măsură Preventivă', 'verbose_name_plural': 'historical Măsuri Preventive'},
        ),
        migrations.AlterModelOptions(
            name='infractiune',
            options={'verbose_name': 'Infracțiune', 'verbose_name_plural': 'Infracțiuni'},
        ),
        migrations.AlterModelOptions(
            name='masurapreventiva',
            options={'verbose_name': 'Măsură Preventivă', 'verbose_name_plural': 'Măsuri Preventive'},
        ),
        migrations.RemoveField(
            model_name='historicalinfractiune',
            name='articol_penal',
        ),
        migrations.RemoveField(
            model_name='infractiune',
            name='articol_penal',
        ),
        migrations.AddField(
            model_name='historicalinfractiune',
            name='act_normativ',
            field=models.CharField(choices=[('CP', 'Codul Penal'), ('CPP', 'Codul de Procedură Penală'), ('OUG195_2002', 'Codul Rutier (OUG 195/2002)'), ('L143_2000', 'Trafic de droguri (Legea 143/2000)'), ('L241_2005', 'Evaziune fiscală (Legea 241/2005)'), ('L50_1991', 'Disciplina în construcții (Legea 50/1991)'), ('ALTUL', 'Alt Act Normativ')], default='CP', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalinfractiune',
            name='articol',
            field=models.CharField(blank=True, help_text='Ex: 228 alin. 1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='infractiune',
            name='act_normativ',
            field=models.CharField(choices=[('CP', 'Codul Penal'), ('CPP', 'Codul de Procedură Penală'), ('OUG195_2002', 'Codul Rutier (OUG 195/2002)'), ('L143_2000', 'Trafic de droguri (Legea 143/2000)'), ('L241_2005', 'Evaziune fiscală (Legea 241/2005)'), ('L50_1991', 'Disciplina în construcții (Legea 50/1991)'), ('ALTUL', 'Alt Act Normativ')], default='CP', max_length=50),
        ),
        migrations.AddField(
            model_name='infractiune',
            name='articol',
            field=models.CharField(blank=True, help_text='Ex: 228 alin. 1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinfractiune',
            name='incadrare_juridica',
            field=models.CharField(blank=True, help_text='Ex: Furt calificat', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infractiune',
            name='incadrare_juridica',
            field=models.CharField(blank=True, help_text='Ex: Furt calificat', max_length=255, null=True),
        ),
    ]
