# Generated by Django 6.0.2 on 2026-03-04 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_historicaldosar_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IstoricDesemnare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('data_desemnare', models.DateField(help_text='Data de la care a preluat dosarul')),
                ('data_finalizare', models.DateField(blank=True, help_text='Data la care a predat dosarul', null=True)),
                ('dosar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istoric_desemnari', to='cases.dosar')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Istoric Desemnare',
                'verbose_name_plural': 'Istoric Desemnări',
                'ordering': ['-data_desemnare'],
            },
        ),
    ]
