# Generated by Django 6.0.2 on 2026-03-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_istoricdesemnare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='istoricdesemnare',
            options={'ordering': ['-data_desemnare', '-id'], 'verbose_name': 'Istoric Desemnare', 'verbose_name_plural': 'Istoric Desemnări'},
        ),
    ]
