# Generated by Django 6.0.2 on 2026-03-09 17:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_istoricdesemnare_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosar',
            name='data_solutiei',
        ),
        migrations.RemoveField(
            model_name='dosar',
            name='stadiu',
        ),
        migrations.RemoveField(
            model_name='dosar',
            name='tip_solutie',
        ),
        migrations.RemoveField(
            model_name='historicaldosar',
            name='data_solutiei',
        ),
        migrations.RemoveField(
            model_name='historicaldosar',
            name='stadiu',
        ),
        migrations.RemoveField(
            model_name='historicaldosar',
            name='tip_solutie',
        ),
        migrations.CreateModel(
            name='HistoricalStadiuCercetare',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tip_stadiu', models.CharField(choices=[('EXAMINARE', 'Examinare sesizare'), ('UP_INCEPUTA', 'Urmărire penală începută'), ('AP_MASCATA', 'Acțiune penală pusă în mișcare')], default='EXAMINARE', max_length=50)),
                ('data_incepere', models.DateField(help_text='Data începerii stadiului')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dosar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.dosar')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Istoric Stadiu',
                'verbose_name_plural': 'historical Stadii Urmărire',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StadiuCercetare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_stadiu', models.CharField(choices=[('EXAMINARE', 'Examinare sesizare'), ('UP_INCEPUTA', 'Urmărire penală începută'), ('AP_MASCATA', 'Acțiune penală pusă în mișcare')], default='EXAMINARE', max_length=50)),
                ('data_incepere', models.DateField(help_text='Data începerii stadiului')),
                ('dosar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadii_cercetare', to='cases.dosar')),
            ],
            options={
                'verbose_name': 'Stadiu Urmărire',
                'verbose_name_plural': 'Stadii Urmărire',
                'ordering': ['-data_incepere'],
            },
        ),
        migrations.CreateModel(
            name='SolutieDosar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stabilita_de', models.CharField(choices=[('ORGAN', 'Organ de cercetare (Propunere)'), ('PROCUROR', 'Procuror (Dispoziție)')], default='ORGAN', max_length=20)),
                ('tip_solutie', models.CharField(choices=[('RECHIZITORIU', 'Rechizitoriu'), ('ACORD', 'Acord de recunoaștere a vinovăției'), ('CLASARE_A', 'Clasare - art. 16 alin. 1 lit. a) fapta nu există'), ('CLASARE_B', 'Clasare - art. 16 alin. 1 lit. b) fapta nu e prevăzută de lege'), ('CLASARE_C', 'Clasare - art. 16 alin. 1 lit. c) nu există probe/nu e săvârșită de inculpat'), ('CLASARE_ALTELE', 'Clasare - alte temeiuri (lit. d-j)'), ('RENUNTARE', 'Renunțare la urmărirea penală'), ('DECLINARE', 'Declinare de competență'), ('TRECERE', 'Trecere la alt organ'), ('RESTITUIRE', 'Restituire la organul de cercetare'), ('ALTA', 'Altă soluție')], max_length=50)),
                ('data_solutiei', models.DateField()),
                ('este_finala', models.BooleanField(default=False, help_text='Bifează dacă aceasta este decizia finală a procurorului')),
                ('stadiu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutii', to='cases.stadiucercetare')),
            ],
            options={
                'verbose_name': 'Soluție Dosar',
                'verbose_name_plural': 'Soluții Dosar',
                'ordering': ['-data_solutiei'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSolutieDosar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('stabilita_de', models.CharField(choices=[('ORGAN', 'Organ de cercetare (Propunere)'), ('PROCUROR', 'Procuror (Dispoziție)')], default='ORGAN', max_length=20)),
                ('tip_solutie', models.CharField(choices=[('RECHIZITORIU', 'Rechizitoriu'), ('ACORD', 'Acord de recunoaștere a vinovăției'), ('CLASARE_A', 'Clasare - art. 16 alin. 1 lit. a) fapta nu există'), ('CLASARE_B', 'Clasare - art. 16 alin. 1 lit. b) fapta nu e prevăzută de lege'), ('CLASARE_C', 'Clasare - art. 16 alin. 1 lit. c) nu există probe/nu e săvârșită de inculpat'), ('CLASARE_ALTELE', 'Clasare - alte temeiuri (lit. d-j)'), ('RENUNTARE', 'Renunțare la urmărirea penală'), ('DECLINARE', 'Declinare de competență'), ('TRECERE', 'Trecere la alt organ'), ('RESTITUIRE', 'Restituire la organul de cercetare'), ('ALTA', 'Altă soluție')], max_length=50)),
                ('data_solutiei', models.DateField()),
                ('este_finala', models.BooleanField(default=False, help_text='Bifează dacă aceasta este decizia finală a procurorului')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stadiu', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.stadiucercetare')),
            ],
            options={
                'verbose_name': 'Istoric Soluție',
                'verbose_name_plural': 'historical Soluții Dosar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
