# Generated by Django 6.0.2 on 2026-03-10 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_remove_dosar_data_solutiei_remove_dosar_stadiu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.CharField(max_length=255)),
                ('link', models.CharField(help_text='URL-ul către dosarul vizat', max_length=255)),
                ('citita', models.BooleanField(default=False)),
                ('data_crearii', models.DateTimeField(auto_now_add=True)),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificare',
                'verbose_name_plural': 'Notificări',
                'ordering': ['-data_crearii'],
            },
        ),
    ]
