# Generated by Django 6.0.2 on 2026-03-12 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_notificare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosar',
            name='data_inregistrarii',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Înregistrării'),
        ),
        migrations.AlterField(
            model_name='dosar',
            name='infractiune_cercetata',
            field=models.TextField(blank=True, help_text='Descrierea faptei pe scurt (opțional)', null=True, verbose_name='Situația de Fapt (Rezumat)'),
        ),
        migrations.AlterField(
            model_name='historicaldosar',
            name='data_inregistrarii',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Înregistrării'),
        ),
        migrations.AlterField(
            model_name='historicaldosar',
            name='infractiune_cercetata',
            field=models.TextField(blank=True, help_text='Descrierea faptei pe scurt (opțional)', null=True, verbose_name='Situația de Fapt (Rezumat)'),
        ),
    ]
