# Generated by Django 6.0.2 on 2026-03-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_alter_dosar_data_inregistrarii_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsolutiedosar',
            name='stabilita_de',
            field=models.CharField(choices=[('ORGAN', 'Organ de cercetare'), ('PROCUROR', 'Procuror')], default='ORGAN', max_length=20),
        ),
        migrations.AlterField(
            model_name='solutiedosar',
            name='stabilita_de',
            field=models.CharField(choices=[('ORGAN', 'Organ de cercetare'), ('PROCUROR', 'Procuror')], default='ORGAN', max_length=20),
        ),
    ]
