# Generated by Django 6.0.2 on 2026-03-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_alter_historicalsolutiedosar_stabilita_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsolutiedosar',
            name='tip_solutie',
            field=models.CharField(choices=[('RECHIZITORIU', 'Rechizitoriu'), ('ACORD', 'Acord de recunoaștere a vinovăției'), ('CLASARE_A', 'Clasare - art. 16 alin. 1 lit. a) fapta nu există'), ('CLASARE_B', 'Clasare - art. 16 alin. 1 lit. b) fapta nu e prevăzută de lege ori nu a fost săvârşită cu vinovăţie'), ('CLASARE_C', 'Clasare - art. 16 alin. 1 lit. c) nu există probe'), ('CLASARE_D', 'Clasare - art. 16 alin. 1 lit. d) există o cauză justificativă sau de neimputabilitate'), ('CLASARE_E', 'Clasare - art. 16 alin. 1 lit. e) lipseşte plângerea prealabilă, autorizarea sau sesizarea ori o altă condiţie'), ('CLASARE_F', 'Clasare - art. 16 alin. 1 lit. f) a intervenit amnistia sau prescripţia, decesul persoanei fizice sau radierea persoanei juridice'), ('CLASARE_G', 'Clasare - art. 16 alin. 1 lit. g) retragerea plângerii prealabile, împăcarea ori încheierea unui acord de mediere'), ('CLASARE_H', 'Clasare - art. 16 alin. 1 lit. h) există o cauză de nepedepsire'), ('CLASARE_I', 'Clasare - art. 16 alin. 1 lit. i) există autoritate de lucru judecat'), ('CLASARE_J', 'Clasare - art. 16 alin. 1 lit. j) a intervenit un transfer de proceduri cu un alt stat'), ('RENUNTARE', 'Renunțare la urmărirea penală'), ('DECLINARE', 'Declinare de competență'), ('TRECERE', 'Trecere la alt organ'), ('RESTITUIRE', 'Restituire la organul de cercetare'), ('ALTA', 'Altă soluție')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solutiedosar',
            name='tip_solutie',
            field=models.CharField(choices=[('RECHIZITORIU', 'Rechizitoriu'), ('ACORD', 'Acord de recunoaștere a vinovăției'), ('CLASARE_A', 'Clasare - art. 16 alin. 1 lit. a) fapta nu există'), ('CLASARE_B', 'Clasare - art. 16 alin. 1 lit. b) fapta nu e prevăzută de lege ori nu a fost săvârşită cu vinovăţie'), ('CLASARE_C', 'Clasare - art. 16 alin. 1 lit. c) nu există probe'), ('CLASARE_D', 'Clasare - art. 16 alin. 1 lit. d) există o cauză justificativă sau de neimputabilitate'), ('CLASARE_E', 'Clasare - art. 16 alin. 1 lit. e) lipseşte plângerea prealabilă, autorizarea sau sesizarea ori o altă condiţie'), ('CLASARE_F', 'Clasare - art. 16 alin. 1 lit. f) a intervenit amnistia sau prescripţia, decesul persoanei fizice sau radierea persoanei juridice'), ('CLASARE_G', 'Clasare - art. 16 alin. 1 lit. g) retragerea plângerii prealabile, împăcarea ori încheierea unui acord de mediere'), ('CLASARE_H', 'Clasare - art. 16 alin. 1 lit. h) există o cauză de nepedepsire'), ('CLASARE_I', 'Clasare - art. 16 alin. 1 lit. i) există autoritate de lucru judecat'), ('CLASARE_J', 'Clasare - art. 16 alin. 1 lit. j) a intervenit un transfer de proceduri cu un alt stat'), ('RENUNTARE', 'Renunțare la urmărirea penală'), ('DECLINARE', 'Declinare de competență'), ('TRECERE', 'Trecere la alt organ'), ('RESTITUIRE', 'Restituire la organul de cercetare'), ('ALTA', 'Altă soluție')], max_length=50),
        ),
    ]
