# Generated by Django 6.0.2 on 2026-03-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_alter_historicalsolutiedosar_tip_solutie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmasurapreventiva',
            name='tip_masura',
            field=models.CharField(choices=[('RETINERE', 'Reținere (24h)'), ('AREST_PREVENTIV', 'Arest preventiv'), ('AREST_DOMICILIU', 'Arest la domiciliu'), ('CONTROL_JUDICIAR', 'Control judiciar'), ('CONTROL_JUDICIAR_CAUTIUNE', 'Control judiciar pe cauțiune')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalparteimplicata',
            name='calitate_procesuala',
            field=models.CharField(choices=[('FAPTUITOR', 'Făptuitor'), ('SUSPECT', 'Suspect'), ('INCULPAT', 'Inculpat'), ('PARTE_VATAMATA', 'Persoană vătămată'), ('PARTE_CIVILA', 'Parte civilă'), ('MARTOR', 'Martor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='masurapreventiva',
            name='tip_masura',
            field=models.CharField(choices=[('RETINERE', 'Reținere (24h)'), ('AREST_PREVENTIV', 'Arest preventiv'), ('AREST_DOMICILIU', 'Arest la domiciliu'), ('CONTROL_JUDICIAR', 'Control judiciar'), ('CONTROL_JUDICIAR_CAUTIUNE', 'Control judiciar pe cauțiune')], max_length=50),
        ),
        migrations.AlterField(
            model_name='parteimplicata',
            name='calitate_procesuala',
            field=models.CharField(choices=[('FAPTUITOR', 'Făptuitor'), ('SUSPECT', 'Suspect'), ('INCULPAT', 'Inculpat'), ('PARTE_VATAMATA', 'Persoană vătămată'), ('PARTE_CIVILA', 'Parte civilă'), ('MARTOR', 'Martor')], max_length=20),
        ),
    ]
