# Generated by Django 6.0.2 on 2026-03-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_alter_historicalmasurapreventiva_tip_masura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinfractiune',
            name='adresa_comiterii',
            field=models.CharField(blank=True, help_text='Ex: Strada Mureșenilor nr. 1, Brașov', max_length=255, null=True, verbose_name='Locul săvârșirii faptei'),
        ),
        migrations.AddField(
            model_name='historicalinfractiune',
            name='latitudine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinfractiune',
            name='longitudine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infractiune',
            name='adresa_comiterii',
            field=models.CharField(blank=True, help_text='Ex: Strada Mureșenilor nr. 1, Brașov', max_length=255, null=True, verbose_name='Locul săvârșirii faptei'),
        ),
        migrations.AddField(
            model_name='infractiune',
            name='latitudine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infractiune',
            name='longitudine',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
