# Generated by Django 6.0.2 on 2026-04-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_historicalinfractiune_adresa_comiterii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparteimplicata',
            name='adresa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresă'),
        ),
        migrations.AddField(
            model_name='parteimplicata',
            name='adresa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresă'),
        ),
    ]
