# Generated by Django 6.0.2 on 2026-04-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_alter_historicalinfractiune_act_normativ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparteimplicata',
            name='numar_ci',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Număr C.I.'),
        ),
        migrations.AddField(
            model_name='historicalparteimplicata',
            name='serie_ci',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Serie C.I.'),
        ),
        migrations.AddField(
            model_name='parteimplicata',
            name='numar_ci',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Număr C.I.'),
        ),
        migrations.AddField(
            model_name='parteimplicata',
            name='serie_ci',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Serie C.I.'),
        ),
        migrations.AlterField(
            model_name='historicalinfractiune',
            name='act_normativ',
            field=models.CharField(choices=[('CP', 'Codul Penal'), ('CPP', 'Codul de Procedură Penală'), ('OUG195_2002', 'Codul Rutier (OUG 195/2002)'), ('L143_2000', 'Trafic de droguri (Legea 143/2000)'), ('L241_2005', 'Evaziune fiscală (Legea 241/2005)'), ('L50_1991', 'Disciplina în construcții (Legea 50/1991)'), ('L217_2003', 'Prevenirea şi combaterea violenţei în familie (Legea 217/2003)'), ('L123_2012', 'Legea energiei electrice şi a gazelor naturale (Legea 123/2012)'), ('ALTUL', 'Alt act normativ')], default='CP', max_length=50),
        ),
        migrations.AlterField(
            model_name='infractiune',
            name='act_normativ',
            field=models.CharField(choices=[('CP', 'Codul Penal'), ('CPP', 'Codul de Procedură Penală'), ('OUG195_2002', 'Codul Rutier (OUG 195/2002)'), ('L143_2000', 'Trafic de droguri (Legea 143/2000)'), ('L241_2005', 'Evaziune fiscală (Legea 241/2005)'), ('L50_1991', 'Disciplina în construcții (Legea 50/1991)'), ('L217_2003', 'Prevenirea şi combaterea violenţei în familie (Legea 217/2003)'), ('L123_2012', 'Legea energiei electrice şi a gazelor naturale (Legea 123/2012)'), ('ALTUL', 'Alt act normativ')], default='CP', max_length=50),
        ),
    ]
