# Generated by Django 6.0.2 on 2026-04-09 12:20

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_alter_historicalsolutiedosar_tip_solutie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparteimplicata',
            name='cnp_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='parteimplicata',
            name='cnp_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalparteimplicata',
            name='cnp',
            field=cases.models.EncryptedTextField(blank=True, null=True, verbose_name='CNP'),
        ),
        migrations.AlterField(
            model_name='parteimplicata',
            name='cnp',
            field=cases.models.EncryptedTextField(blank=True, null=True, verbose_name='CNP'),
        ),
    ]
