# Generated by Django 6.0.2 on 2026-04-09 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_historicalparteimplicata_cnp_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermenProcedural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_termen', models.CharField(choices=[('PRESCRIPTIE_GEN', 'Prescripție Generală'), ('PRESCRIPTIE_SPEC', 'Prescripție Specială'), ('INSTANTA', 'Termen Instanță (Contestație durată)'), ('PROROGARE', 'Termen Prorogare / Declinare'), ('ALTUL', 'Alt tip de termen procedural')], max_length=20, verbose_name='Tip Termen')),
                ('data_limita', models.DateField(verbose_name='Dată Limită / Scadență')),
                ('detalii', models.TextField(blank=True, help_text='Ex: Judecătoria Brașov a stabilit termen pentru finalizarea urmăririi penale.', null=True, verbose_name='Detalii / Observații')),
                ('adaugat_la', models.DateTimeField(auto_now_add=True)),
                ('dosar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termene_procedurale', to='cases.dosar')),
            ],
            options={
                'verbose_name': 'Termen Procedural',
                'verbose_name_plural': 'Termene Procedurale',
                'ordering': ['data_limita'],
            },
        ),
    ]
