# Generated by Django 6.0.2 on 2026-04-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_termenprocedural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termenprocedural',
            name='tip_termen',
            field=models.CharField(choices=[('PRESCRIPTIE_GEN', 'Prescripție Generală'), ('PRESCRIPTIE_SPEC', 'Prescripție Specială'), ('INSTANTA', 'Termen Instanță (Contestație durată)'), ('PROROGARE', 'Termen Prorogare / Declinare'), ('AUDIERE', 'Audiere'), ('ALTUL', 'Alt tip de termen procedural')], max_length=20, verbose_name='Tip Termen'),
        ),
    ]
