# Generated by Django 6.0.2 on 2026-04-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_alter_termenprocedural_tip_termen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termenprocedural',
            options={'ordering': ['data_limita', 'ora'], 'verbose_name': 'Termen Procedural', 'verbose_name_plural': 'Termene Procedurale'},
        ),
        migrations.AddField(
            model_name='termenprocedural',
            name='ora',
            field=models.TimeField(blank=True, help_text='Lăsați gol pentru evenimente care durează toată ziua (ex: Prescripție)', null=True, verbose_name='Oră (Opțional)'),
        ),
        migrations.AddField(
            model_name='termenprocedural',
            name='titlu',
            field=models.CharField(blank=True, default='', help_text='Ex: Audiere martor Popescu. Dacă e lăsat gol, se va genera automat.', max_length=150, verbose_name='Titlu (Scurt)'),
        ),
    ]
