# Generated by Django 6.0.2 on 2026-04-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_alter_termenprocedural_options_termenprocedural_ora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termenprocedural',
            name='indeplinit',
            field=models.BooleanField(default=False, help_text='Bifați dacă activitatea a fost realizată', verbose_name='Îndeplinit'),
        ),
    ]
