# Generated by Django 6.0.2 on 2026-04-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_termenprocedural_indeplinit'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmasurapreventiva',
            name='indeplinit',
            field=models.BooleanField(default=False, verbose_name='Îndeplinit'),
        ),
        migrations.AddField(
            model_name='masurapreventiva',
            name='indeplinit',
            field=models.BooleanField(default=False, verbose_name='Îndeplinit'),
        ),
    ]
