# Generated by Django 6.0.2 on 2026-04-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0028_alter_termenprocedural_tip_termen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termenprocedural',
            name='tip_termen',
            field=models.CharField(choices=[('PRESCRIPTIE_GEN', 'Prescripție'), ('PRESCRIPTIE_SPEC', 'Prescripție Specială'), ('INSTANTA', 'Termen instanță (Contestație durată proces)'), ('AUDIERE', 'Audiere'), ('ALTUL', 'Alt tip de termen procedural')], max_length=20, verbose_name='Tip Termen'),
        ),
    ]
