# Generated by Django 6.0.2 on 2026-04-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0029_alter_termenprocedural_tip_termen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termenprocedural',
            name='tip_termen',
            field=models.CharField(choices=[('PRESCRIPTIE_GEN', 'Prescripție'), ('NOTA', 'Notă de dispoiţii'), ('INSTANTA', 'Termen instanță (Contestație durată proces)'), ('AUDIERE', 'Audiere'), ('ALTUL', 'Alt tip de termen procedural')], max_length=20, verbose_name='Tip Termen'),
        ),
    ]
