# Generated by Django 6.0.2 on 2026-04-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_alter_termenprocedural_tip_termen'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparteimplicata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresă email'),
        ),
        migrations.AddField(
            model_name='parteimplicata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresă email'),
        ),
    ]
