# Generated by Django 6.0.2 on 2026-05-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0032_historicalparteimplicata_email_parteimplicata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificare',
            name='tip',
            field=models.CharField(choices=[('DOCUMENT', 'Document adăugat'), ('TERMEN', 'Termen procedural'), ('STADIU', 'Stadiu / soluție'), ('PORTAL', 'Cerere portal'), ('MASURA', 'Măsură preventivă'), ('EMAIL', 'Email trimis'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
    ]
