# Generated by Django 6.0.2 on 2026-04-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='totp_activ',
            field=models.BooleanField(default=False, verbose_name='2FA Activ'),
        ),
    ]
