# Generated by Django 6.0.2 on 2026-04-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_totp_activ'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='certificat_pem',
            field=models.TextField(blank=True, help_text='Certificatul public X.509 al utilizatorului', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cheie_privata_criptata',
            field=models.BinaryField(blank=True, help_text='Cheia privată RSA criptată cu Fernet', null=True),
        ),
    ]
