# Generated by Django 6.0.2 on 2026-02-24 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActUrmarire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=255)),
                ('tip', models.CharField(choices=[('ORDONANTA', 'Ordonanță'), ('REFERAT', 'Referat'), ('DECLARATIE', 'Declarație'), ('PROCES_VERBAL', 'Proces-Verbal'), ('ALTUL', 'Alt tip de act')], default='ORDONANTA', max_length=20)),
                ('fisier', models.FileField(upload_to='acte_penale/%Y/%m/')),
                ('data_incarcarii', models.DateTimeField(auto_now_add=True)),
                ('descriere_scurta', models.TextField(blank=True, help_text='Rezumatul actului (opțional)', null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dosar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documente', to='cases.dosar')),
            ],
            options={
                'verbose_name': 'Act de Urmărire Penală',
                'verbose_name_plural': 'Acte de Urmărire Penală',
                'ordering': ['-data_incarcarii'],
            },
        ),
    ]
