# Generated by Django 6.0.2 on 2026-03-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acturmarire',
            name='tip',
            field=models.CharField(choices=[('ORDONANTA', 'Ordonanță'), ('REFERAT', 'Referat'), ('DECLARATIE', 'Declarație'), ('PROCES_VERBAL', 'Proces-Verbal'), ('ALTUL', 'Alt tip de act')], default='ORDONANTA', max_length=50),
        ),
        migrations.AlterField(
            model_name='acturmarire',
            name='titlu',
            field=models.CharField(blank=True, help_text='Lăsați gol dacă titlul coincide cu tipul documentului', max_length=255, null=True),
        ),
    ]
