# Generated by Django 6.0.2 on 2026-03-12 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_acturmarire_tip_alter_acturmarire_titlu'),
    ]

    operations = [
        migrations.AddField(
            model_name='acturmarire',
            name='data_documentului',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data scrisă pe actul fizic', verbose_name='Data emiterii documentului'),
        ),
        migrations.AddField(
            model_name='acturmarire',
            name='data_inregistrarii',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data la care a primit număr de intrare/înregistrare', verbose_name='Data înregistrării'),
        ),
    ]
