# Generated by Django 6.0.2 on 2026-03-24 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_acturmarire_data_documentului_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acturmarire',
            name='data_documentului',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data emiterii/întocmirii documentului', verbose_name='Data emiterii documentului'),
        ),
        migrations.AlterField(
            model_name='acturmarire',
            name='data_inregistrarii',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data atribuirii numărului de intrare/înregistrare', verbose_name='Data înregistrării'),
        ),
    ]
