# Generated by Django 6.0.2 on 2026-04-08 16:20

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_acturmarire_data_documentului_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acturmarire',
            name='fisier',
            field=models.FileField(upload_to=documents.models.cale_upload_document, validators=[documents.models.valideaza_extensie_document, documents.models.valideaza_dimensiune_document], verbose_name='Fișier Document'),
        ),
    ]
