# Generated by Django 6.0.2 on 2026-04-11 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_acturmarire_fisier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acturmarire',
            name='data_semnarii',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acturmarire',
            name='este_semnat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acturmarire',
            name='fisier_semnat',
            field=models.FileField(blank=True, help_text='Varianta finală, securizată cu semnătură digitală', null=True, upload_to='documente/semnate/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='acturmarire',
            name='semnat_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acte_semnate_de_mine', to=settings.AUTH_USER_MODEL),
        ),
    ]
