# Generated by Django 6.0.2 on 2026-04-30 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_acturmarire_data_semnarii_acturmarire_este_semnat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrimiterePrinEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimis_la', models.DateTimeField(auto_now_add=True)),
                ('email_destinatar', models.EmailField(max_length=254)),
                ('nume_destinatar', models.CharField(max_length=200)),
                ('subiect', models.CharField(max_length=255)),
                ('mesaj', models.TextField(blank=True)),
                ('reusit', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimiteri_email', to='documents.acturmarire')),
                ('trimis_de', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emailuri_trimise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trimitere email document',
                'verbose_name_plural': 'Trimiteri email documente',
                'ordering': ['-trimis_la'],
            },
        ),
    ]
