# Generated by Django 6.0.2 on 2026-05-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_trimitereprinemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimitereprinemail',
            name='varianta_trimisa',
            field=models.CharField(choices=[('original', 'Original'), ('semnat', 'Semnat')], default='original', max_length=10),
        ),
    ]
